version: '3'
services:

  mongodb:
    hostname: mongodb
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  railplan:
    hostname: railplan
    image: railplan
    container_name: railplan
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 8080:8080
    environment:
      MONGO_DB_HOST: mongodb
