name: Build & Test

on: [push]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install ChromeDriver for End-to-End tests
      # taken from https://github.com/actions/virtual-environments/issues/9#issuecomment-555949137
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
          && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
          && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
          && cd /tmp \
          && unzip chromedriver_linux64.zip \
          && rm -rf chromedriver_linux64.zip \
          && sudo mv chromedriver /usr/local/bin/chromedriver \
          && sudo chmod +x /usr/local/bin/chromedriver \
          && chromedriver --version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

#    - name: Run Unit Tests
#      run: mvn surefire:test@unit-tests

#    - name: Run Acceptance Tests
#      run: mvn surefire:test@acceptance-tests

    - name: Start Docker Environment
      run: docker-compose -f docker-compose.yml up -d

#    - name: Run Integration Tests
#      run: mvn surefire:test@integration-tests

    - name: Create Test Coverage Report
      run: mvn verify jacoco:report

    - name: Upload Coverage Report to Codacy
      run: CODACY_PROJECT_TOKEN=534003747f564ae5b69ee679e4c063b4 bash <(curl -Ls https://coverage.codacy.com/get.sh)

    - name: Destroy Docker Environment
      run: docker-compose down
