name: Build & Test

on: [push]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install ChromeDriver for End-to-End tests
      # taken from https://github.com/actions/virtual-environments/issues/9#issuecomment-555949137
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
          && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
          && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
          && cd /tmp \
          && unzip chromedriver_linux64.zip \
          && rm -rf chromedriver_linux64.zip \
          && sudo mv chromedriver /usr/local/bin/chromedriver \
          && sudo chmod +x /usr/local/bin/chromedriver \
          && chromedriver --version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Start Docker Environment
      run: docker-compose -f docker-compose.yml up -d

    - name: Run Tests
      run: mvn verify jacoco:report

    - name: Upload Coverage Report to Codacy
      # taken from https://github.com/codacy/codacy-coverage-reporter
      run: export CODACY_PROJECT_TOKEN=534003747f564ae5b69ee679e4c063b4
        && curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
        && chmod +x codacy-coverage-reporter
        && ./codacy-coverage-reporter report -l Java -r 01-domain/target/site/jacoco/jacoco.xml --partial
        && ./codacy-coverage-reporter report -l Java -r 02-application/target/site/jacoco/jacoco.xml --partial
        && ./codacy-coverage-reporter report -l Java -r 04-userinterface/target/site/jacoco/jacoco.xml --partial
        && ./codacy-coverage-reporter final

    - name: Destroy Docker Environment
      run: docker-compose down
