name: Build

on: [push]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Unit Tests
      run: mvn surefire:test@unit-tests

    - name: Run Acceptance Tests
      run: mvn surefire:test@acceptance-tests

    - name: Start Docker Environment
      run: docker-compose -f docker-compose.yml up -d

    - name: Run Integration Tests
      run: mvn surefire:test@integration-tests

    - name: Destroy Docker Environment
      run: docker-compose down
